server:
  port: 9001
spring:
  application:
    name: social-base
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true